{
    "status": "success",
    "data": [
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100077082",
            "exchange_order_id": "1600000003730941",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:20:00",
            "exchange_update_timestamp": "2025-06-16 09:20:00",
            "exchange_timestamp": "2025-06-16 09:20:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800PE",
            "instrument_token": 13056514,
            "order_type": "MARKET",
            "transaction_type": "SELL",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 156.40769231000002,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060Xz1276VwauUFg"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100077111",
            "exchange_order_id": "1600000003732076",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:20:00",
            "exchange_update_timestamp": "2025-06-16 09:20:00",
            "exchange_timestamp": "2025-06-16 09:20:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800CE",
            "instrument_token": 13056258,
            "order_type": "MARKET",
            "transaction_type": "SELL",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 141.78846154000001,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060XpUg5VjD2GcEA"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100077152",
            "exchange_order_id": "1600000003735316",
            "parent_order_id": null,
            "status": "CANCELLED",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:31:55",
            "exchange_update_timestamp": "2025-06-16 09:31:55",
            "exchange_timestamp": "2025-06-16 09:20:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800CE",
            "instrument_token": 13056258,
            "order_type": "SL",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 183.5,
            "trigger_price": 181.5,
            "average_price": 0,
            "filled_quantity": 0,
            "pending_quantity": 975,
            "cancelled_quantity": 975,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060XUT14eYF33Map"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100077160",
            "exchange_order_id": "1600000003741478",
            "parent_order_id": null,
            "status": "CANCELLED",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:31:55",
            "exchange_update_timestamp": "2025-06-16 09:31:55",
            "exchange_timestamp": "2025-06-16 09:20:01",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800PE",
            "instrument_token": 13056514,
            "order_type": "SL",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 202,
            "trigger_price": 200,
            "average_price": 0,
            "filled_quantity": 0,
            "pending_quantity": 975,
            "cancelled_quantity": 975,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060XQSSHNdwUfB4H"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100170785",
            "exchange_order_id": "1600000011332303",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:31:55",
            "exchange_update_timestamp": "2025-06-16 09:31:55",
            "exchange_timestamp": "2025-06-16 09:31:55",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800PE",
            "instrument_token": 13056514,
            "order_type": "MARKET",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 147.26153846,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060Xe1uO20zjhyrD"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100170804",
            "exchange_order_id": "1600000011333188",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 09:31:55",
            "exchange_update_timestamp": "2025-06-16 09:31:55",
            "exchange_timestamp": "2025-06-16 09:31:55",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924800CE",
            "instrument_token": 13056258,
            "order_type": "MARKET",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 139.56923077,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "6sPvDBi0",
            "tags": [
                "6sPvDBi0"
            ],
            "guid": "33060XJuhlZglS5Zxb"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100381849",
            "exchange_order_id": "1000000037185477",
            "parent_order_id": null,
            "status": "TRIGGER PENDING",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 10:15:02",
            "exchange_update_timestamp": "2025-06-16 10:15:02",
            "exchange_timestamp": "2025-06-16 10:15:02",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY25JUNFUT",
            "instrument_token": 14536962,
            "order_type": "SL",
            "transaction_type": "SELL",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "NRML",
            "quantity": 225,
            "disclosed_quantity": 0,
            "price": 24730,
            "trigger_price": 24735,
            "average_price": 0,
            "filled_quantity": 0,
            "pending_quantity": 225,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "chase",
            "tags": [
                "chase"
            ],
            "guid": "33060Xje9y40uAike1"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100552020",
            "exchange_order_id": "1100000053785773",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 11:00:00",
            "exchange_update_timestamp": "2025-06-16 11:00:00",
            "exchange_timestamp": "2025-06-16 11:00:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924900PE",
            "instrument_token": 13058050,
            "order_type": "MARKET",
            "transaction_type": "SELL",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 147.39615385,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "w1OLLOfO",
            "tags": [
                "w1OLLOfO"
            ],
            "guid": "33060X5O9b1zTqsI6F"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100552022",
            "exchange_order_id": "1100000053786181",
            "parent_order_id": null,
            "status": "COMPLETE",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 11:00:00",
            "exchange_update_timestamp": "2025-06-16 11:00:00",
            "exchange_timestamp": "2025-06-16 11:00:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924900CE",
            "instrument_token": 13057794,
            "order_type": "MARKET",
            "transaction_type": "SELL",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 0,
            "trigger_price": 0,
            "average_price": 145.52307692,
            "filled_quantity": 975,
            "pending_quantity": 0,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "w1OLLOfO",
            "tags": [
                "w1OLLOfO"
            ],
            "guid": "33060XOq2y0j57CXOn"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100552035",
            "exchange_order_id": "1100000053788506",
            "parent_order_id": null,
            "status": "TRIGGER PENDING",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 11:00:00",
            "exchange_update_timestamp": "2025-06-16 11:00:00",
            "exchange_timestamp": "2025-06-16 11:00:00",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924900CE",
            "instrument_token": 13057794,
            "order_type": "SL",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 186.5,
            "trigger_price": 185,
            "average_price": 0,
            "filled_quantity": 0,
            "pending_quantity": 975,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "w1OLLOfO",
            "tags": [
                "w1OLLOfO"
            ],
            "guid": "33060X1p1S68eAICLZ"
        },
        {
            "account_id": "ZZ0829",
            "placed_by": "ZZ0829",
            "order_id": "250616100552040",
            "exchange_order_id": "1100000053789703",
            "parent_order_id": null,
            "status": "TRIGGER PENDING",
            "status_message": null,
            "status_message_raw": null,
            "order_timestamp": "2025-06-16 11:00:01",
            "exchange_update_timestamp": "2025-06-16 11:00:01",
            "exchange_timestamp": "2025-06-16 11:00:01",
            "variety": "regular",
            "modified": false,
            "exchange": "NFO",
            "tradingsymbol": "NIFTY2561924900PE",
            "instrument_token": 13058050,
            "order_type": "SL",
            "transaction_type": "BUY",
            "validity": "DAY",
            "validity_ttl": 0,
            "product": "MIS",
            "quantity": 975,
            "disclosed_quantity": 0,
            "price": 189,
            "trigger_price": 187,
            "average_price": 0,
            "filled_quantity": 0,
            "pending_quantity": 975,
            "cancelled_quantity": 0,
            "market_protection": 0,
            "meta": {},
            "tag": "w1OLLOfO",
            "tags": [
                "w1OLLOfO"
            ],
            "guid": "33060XLSo931HSjm1r"
        }
    ]
}

response when order is breached

{
  status: "error",
  message: "Trigger price for stoploss buy orders should be higher than the last traded price (24950.00). Use limit order to buy at a lower price. [Read more.](https://support.zerodha.com/category/trading-and-markets/margin-leverage-and-product-and-order-types/articles/what-are-stop-loss-orders-and-how-to-use-them)",
  data: null,
  error_type: "InputException"
}

Fetching candles for NIFTY25JULFUT and token 13623298 from 2025-06-26 14:59:05 to 2025-06-26 15:00:05 